### ISSUE TITLE
Windows defender alerts that underrailpatcher.dll is trojan

### ISSUE THREAD

**Issue by tuasq** [klowd92/underrail_developers_console#4]
Is this false positive? i know its most likely be it but just in case i'll write it here and wait for comment before playing

**Comment by tuasq** [comment]
i went to virustotal for check and only one vender triggered alert, weird but probably safe to use.

**Comment by klowd92** [comment]
Hey, i'm not sure why it gives those warnings.. The source code is very short and simple..
I think VirusTotal should clear it with virtually all vendors like you said.

If anyone wants to be safe, he can build it straight from the source code. 
All you need is microsoft visual studio community edition. I gave instructions in the README.
